In [4]:
import torch
# 实现一个num_layers层的LSTM-RNN
class RNN(torch.nn.Module):
    def __init__(self,input_size, hidden_size, num_layers):
        super(RNN,self).__init__()
        self.input_size = input_size
        self.hidden_size=hidden_size
        self.num_layers=num_layers
        self.lstm = torch.nn.LSTM(input_size=input_size,hidden_size=hidden_size,num_layers=num_layers,batch_first=False)
    
    def forward(self,input):
        # input应该为(batch_size,seq_len,input_szie)
        self.hidden = self.initHidden(input.size(1))
        out,self.hidden = self.lstm(input,self.hidden)
        return out,self.hidden
    
    def initHidden(self,batch_size):
        if self.lstm.bidirectional:
            return (torch.rand(self.num_layers*2,batch_size,self.hidden_size),torch.rand(self.num_layers*2,batch_size,self.hidden_size))
        else:
            return (torch.rand(self.num_layers,batch_size,self.hidden_size),torch.rand(self.num_layers,batch_size,self.hidden_size))

input_size = 12
hidden_size = 10
num_layers = 3
batch_size = 2
model = RNN(input_size,hidden_size,num_layers)
# input (seq_len, batch, input_size) 包含特征的输入序列，如果设置了batch_first，则batch为第一维
input = torch.rand(2,4,12)
model(input)

(tensor([[[ 0.0569,  0.3682,  0.2133,  0.0476,  0.2376,  0.1589, -0.0052,
            0.1590,  0.1072,  0.0216],
          [ 0.1053,  0.0610,  0.2369,  0.0147,  0.2249,  0.1357,  0.0152,
            0.0290,  0.0837,  0.1499],
          [ 0.2017,  0.1203,  0.2076,  0.0205,  0.2493,  0.1089,  0.0089,
           -0.0586,  0.1051, -0.0259],
          [ 0.0917,  0.2015,  0.1172, -0.0227,  0.2657,  0.0710,  0.0733,
            0.1241,  0.0521, -0.0917]],
 
         [[ 0.0132,  0.2133,  0.1737,  0.0172,  0.2109,  0.0458, -0.0728,
            0.0787, -0.0498, -0.1009],
          [ 0.0277,  0.0638,  0.2087, -0.0159,  0.1455,  0.0272, -0.0667,
            0.0025, -0.0551, -0.0341],
          [ 0.1021,  0.0711,  0.1841, -0.0400,  0.1866,  0.0257, -0.0844,
           -0.0382, -0.0356, -0.1085],
          [ 0.0270,  0.1154,  0.1291, -0.0442,  0.1953, -0.0032, -0.0270,
            0.0519, -0.0702, -0.1579]]], grad_fn=<StackBackward>),
 (tensor([[[-0.0189,  0.0300,  0.0944, -0.0563, -0.0623,  0.1557,

In [8]:
import torch.nn as nn
m = nn.Softmax2d()
# you softmax over the 2nd dimension
input = torch.randn(2, 3, 12, 13)
output = m(input)
print(output.size())

torch.Size([2, 3, 12, 13])


In [20]:
import torch
 
a = torch.Tensor([1,2])
a1 = a.unsqueeze(0)
print(a)
print(a1.size())

tensor([1., 2.])
torch.Size([1, 2])
